# Generated by Django 3.0.8 on 2020-08-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0004_auto_20200823_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='date_missing',
            field=models.DateField(verbose_name='date of call'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='reason',
            field=models.CharField(max_length=255),
        ),
    ]
